apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: {{ .Values.backend.replicaCount }}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flaskapp
        image: {{ .Values.backend.containers.flaskappImage }}
        imagePullPolicy: Always
        env:
        - name: APP_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: FIBONACCI_SVC_NAME
          value: {{ printf "%s-%s" .Release.Name .Values.fibonacci.servicePrefix }}
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-proxy-config
        configMap:
          name: nginx-config