apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.fibonacci.servicePrefix }}
spec:
  selector:
    app: fibonacci
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80